const INITIAL_PRESENTERS = [
  {id:1,name:'Laura Phelan',pin:'5838',brands:[]},
  {id:2,name:'Liam Dixon',pin:'9951',brands:[]},
  {id:3,name:'Lily Fisher',pin:'4214',brands:['PerfectTed']},
  {id:4,name:'Lily Taylor',pin:'2001',brands:[]},
  {id:5,name:'Linda Scaramella',pin:'3443',brands:[]},
  {id:6,name:'Lithasa Orlando',pin:'2596',brands:[]},
  {id:7,name:'Louis Wilson',pin:'',brands:[]},
  {id:8,name:'Lucrezia Phifer',pin:'4304',brands:[]},
  {id:9,name:'Lucy White',pin:'5323',brands:['Nala's Baby']},
  {id:10,name:'Malak Yasser',pin:'3404',brands:[]},
  {id:11,name:'Maria Lopiano',pin:'5273',brands:['LoveCorn','The Flavour Vault']},
  {id:12,name:'Marina Pownall',pin:'0989',brands:['Centrum','Plenish','The Flavour Vault']},
  {id:13,name:'Martha Godber',pin:'6824',brands:['The Gut Stuff','Trip']},
  {id:14,name:'Matt Jolly',pin:'4085',brands:['Biodance','Lola's Cupcakes','PerfectTed','Sweet Bee Organics']},
  {id:15,name:'Mel Saggs',pin:'3917',brands:['Flo','PerfectTed','Trip']},
  {id:16,name:'Melisa Ceron Gonzalez',pin:'8016',brands:[]},
  {id:17,name:'Mikey Aveline',pin:'5556',brands:['Fussy','Ghost','The Body Shop']},
  {id:18,name:'Millie Gaston',pin:'2309',brands:[]},
  {id:19,name:'Millie Scott',pin:'4804',brands:['Centrum','Humantra','Fuel10k']},
  {id:20,name:'Moresha Ibele',pin:'4379',brands:['Humantra']},
  {id:21,name:'Muireann Ryan',pin:'6931',brands:[]},
  {id:22,name:'Natalie Acquaye-Nortey',pin:'1902',brands:['Flo','XOXO']},
  {id:23,name:'Natalie Ava Nasr',pin:'5761',brands:['Biodance','Mixsoon']},
  {id:24,name:'Natasha Michael',pin:'8819',brands:[]},
  {id:25,name:'Nathalie Millet',pin:'0109',brands:[]},
  {id:26,name:'Nazan Husseyin',pin:'9875',brands:['Ghost','Nala's Baby']},
  {id:27,name:'Olga Buccola',pin:'2903',brands:[]},
  {id:28,name:'Oliver Pittam',pin:'9064',brands:['Centrum']},
  {id:29,name:'Olivia McGuinness',pin:'8998',brands:['Trip']},
  {id:30,name:'Patrick Fusco',pin:'7657',brands:[]},
  {id:31,name:'Rob White',pin:'9460',brands:[]},
  {id:32,name:'Robert',pin:'',brands:['Lola's Cupcakes']},
  {id:33,name:'Rosie Musk',pin:'9332',brands:[]},
  {id:34,name:'Ryan Hand',pin:'0785',brands:[]},
  {id:35,name:'Sam Tuffs',pin:'3764',brands:[]},
  {id:36,name:'Sarah MacKenzie',pin:'1678',brands:['Lola's Cupcakes','LoveCorn']},
  {id:37,name:'Scott McGlynn',pin:'9900',brands:['The Gut Stuff','Hairsyrup']},
  {id:38,name:'Seb Slade',pin:'6827',brands:[]},
  {id:39,name:'Shahlaa Tahira',pin:'7222',brands:['Nala's Baby']},
  {id:40,name:'Sophie Béphage',pin:'2413',brands:['Lola's Cupcakes']},
  {id:41,name:'Stefan Evans',pin:'0496',brands:['Bibigo','Centrum','Trip']},
  {id:42,name:'Tallulah Wrey',pin:'8910',brands:[]},
  {id:43,name:'Tamara Wilder',pin:'5175',brands:['Plenish']},
  {id:44,name:'Thomas Brackley',pin:'4363',brands:[]},
  {id:45,name:'Tina Pisacane',pin:'1411',brands:['Fussy','Trip']},
  {id:46,name:'Tom Williets',pin:'3450',brands:['Humantra','Plenish','The Flavour Vault']},
  {id:47,name:'Veneza Robins',pin:'7936',brands:['Trip']},
  {id:48,name:'Adam Goldsmith',pin:'0401',brands:['The Gut Stuff']},
  {id:49,name:'Adelah Bilal',pin:'1578',brands:[]},
  {id:50,name:'Alexandria Hayden',pin:'6733',brands:['Biodance']},
  {id:51,name:'Alexis Economou',pin:'0638',brands:['Flo']},
  {id:52,name:'Amaka Asiegbu',pin:'7260',brands:[]},
  {id:53,name:'Anna Ivanova',pin:'2404',brands:[]},
  {id:54,name:'Anoushka Chadha',pin:'6259',brands:[]},
  {id:55,name:'Arnica Miakista',pin:'6680',brands:[]},
  {id:56,name:'Autumn Shields',pin:'9962',brands:[]},
  {id:57,name:'Azeez T Oyediran',pin:'7344',brands:[]},
  {id:58,name:'Belinda Normsaskul',pin:'9545',brands:['Mixsoon','Trip']},
  {id:59,name:'BethanyRose Smith',pin:'3731',brands:['Biodance']},
  {id:60,name:'Bex Kealy',pin:'2504',brands:[]},
  {id:61,name:'Bianca Muscatelli',pin:'0185',brands:['Flo']},
  {id:62,name:'Billy Gurney',pin:'8142',brands:[]},
  {id:63,name:'Billy Truswell',pin:'9322',brands:['Plenish']},
  {id:64,name:'Brian Maitland',pin:'3999',brands:[]},
  {id:65,name:'Briliana Duneva',pin:'4505',brands:['Mixsoon','Trip','XOXO']},
  {id:66,name:'Carla',pin:'',brands:['Fuel10k','Ghost']},
  {id:67,name:'Carlo Boumouglbay',pin:'3446',brands:[]},
  {id:68,name:'Chloe Graham',pin:'1235',brands:[]},
  {id:69,name:'Ciara Morris',pin:'8186',brands:[]},
  {id:70,name:'DaisieBelle Downer',pin:'5681',brands:['Fussy','Sweet Bee Organics','Sodastream']},
  {id:71,name:'Deborah Brown',pin:'',brands:['Nala's Baby']},
  {id:72,name:'Dominic Quinn',pin:'5496',brands:[]},
  {id:73,name:'Eki Maria',pin:'5241',brands:['Sodastream']},
  {id:74,name:'Emily Cochrane',pin:'',brands:[]},
  {id:75,name:'Emma Cargill',pin:'9989',brands:[]},
  {id:76,name:'Emma Knudsen',pin:'4972',brands:['Mixsoon']},
  {id:77,name:'Evie Farquharson',pin:'0872',brands:[]},
  {id:78,name:'Francesca Victory',pin:'1880',brands:['Flo','Fussy']},
  {id:79,name:'Gabrielle Richens',pin:'',brands:[]},
  {id:80,name:'Gareth James McLaughlin',pin:'5029',brands:['Trip']},
  {id:81,name:'Genevieve Labuschagne',pin:'2344',brands:[]},
  {id:82,name:'Georgia Louise McPhee',pin:'5046',brands:[]},
  {id:83,name:'Georgina Newton',pin:'7259',brands:['LoveCorn','The Gut Stuff']},
  {id:84,name:'Hannah Dettmer',pin:'2821',brands:['Sodastream','Trip']},
  {id:85,name:'Harrison Hartley',pin:'8944',brands:[]},
  {id:86,name:'Hattie Carter',pin:'2321',brands:['Humantra','Trip']},
  {id:87,name:'Hayley Walsh',pin:'3494',brands:[]},
  {id:88,name:'Helena Bowles',pin:'5487',brands:['PerfectTed']},
  {id:89,name:'Henry Muller',pin:'6695',brands:['Ghost','Humantra']},
  {id:90,name:'Hilda Cronje',pin:'5024',brands:['Centrum']},
  {id:91,name:'Imogen Kingsley Smith',pin:'1866',brands:[]},
  {id:92,name:'Iveta Degulyte',pin:'9078',brands:[]},
  {id:93,name:'Jack Adam Goward',pin:'6966',brands:[]},
  {id:94,name:'Jasmine Raymond',pin:'7704',brands:[]},
  {id:95,name:'Jennyfer Walker',pin:'9212',brands:['Trip']},
  {id:96,name:'Josephine Helen Rogers',pin:'2392',brands:['Sweet Bee Organics']},
  {id:97,name:'Katherine Gibbons',pin:'',brands:['Biodance','Mixsoon','PerfectTed']},
];

const INITIAL_BRANDS = [
  'Bibigo',
  'Biodance',
  'Centrum',
  'Flo',
  'Fuel10k',
  'Fussy',
  'Ghost',
  'Hairsyrup',
  'Humantra',
  'Lola\'s Cupcakes',
  'LoveCorn',
  'Mixsoon',
  'Nala\'s Baby',
  'PerfectTed',
  'Plenish',
  'Sodastream',
  'Sweet Bee Organics',
  'The Body Shop',
  'The Flavour Vault',
  'The Gut Stuff',
  'Trip',
  'XOXO'
];
